id: I8A1491AC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T07:17:34+00:00'
last_modified: '2022-06-07T17:04:14.228314+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22308
  title: ཐོད་པ་བཟང་ངན་བརྟག་ཐབས་དང་བཞེད་ཧོར་བསང་མཆོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    2DBD:
      image_group_id: I1KG9611
      title: ''
      total_pages: 30
      order: 1
      base_file: 2DBD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
