id: P003021
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 10:34:49.173503
source_metadata:
  id: bdr:W22308
  title: ཐོད་པ་བཟང་ངན་བརྟག་ཐབས་དང་བཞེད་ཧོར་བསང་མཆོད།
  author: ''
  volumes:
    daf4b1af9ca945b097c9c9b8209bcaee:
      image_group_id: I1KG9611
      title: ''
      volume_number: 1
      total_pages: 30
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
